config/routes.rb
Multitenant::Application.routes.draw do
  resources :blogs
  resources :home
  get '/', to: 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def set_blog
    @blog = Blog.where(subdomain: request.subdomains.first).first!

    search_paths = [request.subdomains.first, 'public'].compact.join(',')
    ActiveRecord::Base.connection.schema_search_path = search_paths

    Rails.logger.info "Multitenancy: search_path was set to: #{search_paths}"
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog

  def index
    @blogs = Blog.all
  end

  def show

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_blog

  def index
    render 'blogs/show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/index.html.erb
All blogs:

<ul>
  <% @blogs.each do |blog| %>
    <li>
    <%# <%= link_to blog.name, url_for("#{blog.subdomain}.#{request.url}") %>
    <%= link_to blog.name, "#{request.protocol}#{blog.subdomain}.#{request.host}" %>
    <%= link_to blog.name, blog_url(blog) %>
    </li>
  <% end %>
</ul>

app/views/blogs/show.html.erb
Name: <%= @blog.name %>
Subdomain: <%= @blog.subdomain %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Multitenant</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>